#YAML
percentage_vol_target: 24
notional_trading_capital: 32000
base_currency: "GBP"
trading_rules:
  smac16_64:
    function: systems.leveraged_trading.rules.smac
    data:
      - "rawdata.get_daily_prices"
    other_args:
      fast: 16
      slow: 64
    #forecast_scalar: 0.5712
#  ewmac16_64:
#     function: systems.provided.example.rules.ewmac_forecast_with_defaults
#     data: data.daily_prices
#     other_args:
#         Lfast: 16
#         Lslow: 64

forecast_cap: 20.0
#
# forecast combination
#
forecast_weights:
  smac16_64: 1.00
#forecast_div_multiplier: 1.31

#use_forecast_scale_estimates: True

#instrument_weights:
#    CORN: 1.0

#volatility_calculation:
#  func: "sysquant.estimators.vol.robust_vol_calc"
#  days: 25
#  min_periods: 10
#  vol_abs_min: 0.0000000001
#  vol_floor: True
#  floor_min_quant: 0.05
#  floor_min_periods: 100
#  floor_days: 500

#
# Portfolio creation
#
instrument_weights:
    BUND: 0.20
    SP500: 0.20
    GOLD: 0.20
    NZD: 0.20
    CORN: 0.20
instrument_div_multiplier: 1.89

ignore_instruments:
  - KOSPI