#YAML
percentage_vol_target: 24
notional_trading_capital: 20000
base_currency: "GBP"
trading_rules:
  rasmac16_64:
    function: systems.leveraged_trading.rules.rasmac
    data:
      - "rawdata.get_daily_prices"
    other_args:
      fast: 16
      slow: 64
    #forecast_scalar: 57.12
#  ewmac16_64:
#     function: systems.provided.example.rules.ewmac_forecast_with_defaults
#     data: data.daily_prices
#     other_args:
#         Lfast: 16
#         Lslow: 64

#instrument_weights:
#    CORN: 1.0

volatility_calculation:
  func: "sysquant.estimators.vol.robust_vol_calc"
  days: 35
  min_periods: 10
  vol_abs_min: 0.0000000001
  vol_floor: True
  floor_min_quant: 0.05
  floor_min_periods: 100
  floor_days: 500