#instruments: ['BUXL','CHF','DAX','CRUDE_W','GOLD','NASDAQ','EURGBP','US30','SOYOIL']
#instruments: ['GOLD', 'CARBON', 'BUXL', 'EUROSTX', 'LEANHOG', 'CHF', 'OJ', 'COPPER', 'RUSSELL', 'COCOA_NY', 'CRUDE_W', 'EURGBP']
instruments: ["NASDAQ","US30","GOLD","DAX","BUXL","CARBON","HANG","GILT","CRUDE_W","EUROSTX"]
#instruments: ["NASDAQ","US30","GOLD","DAX","BUXL","CARBON","NIKKEI","GILT","CRUDE_W","LEANHOG"]

#
#use_forecast_scale_estimates: True
#
forecast_scalar_estimate:
   pool_instruments: True
#
# forecast combination
#
use_forecast_weight_estimates: True
use_forecast_div_mult_estimates: True

#
forecast_correlation_estimate:
   pool_instruments: True
#
use_instrument_weight_estimates: True
use_instrument_div_mult_estimates: True




