#YAML
#
# Raw data
#
#
# Trading rules
#
trading_rules:
  ewmac2_8:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8
     forecast_scalar: 13.897708051891179
  ewmac4_16:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16
     forecast_scalar: 9.687993745959428
  ewmac8_32:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32
     forecast_scalar: 6.718732931285525
  ewmac16_64:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
     forecast_scalar: 4.611155161940884
  ewmac32_128:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128
     forecast_scalar: 3.074357119655996
  ewmac64_256:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.9994733347399993
  carry:
     function: systems.provided.futures_chapter15.rules.carry2
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 90
     forecast_scalar: 30.84311168398823

# forecast combination
#

forecast_weights:
  BUND:
    carry: 0.7823130036531172
    ewmac16_64: 8.372915808047777e-18
    ewmac2_8: 3.067991876248172e-17
    ewmac32_128: 0.10884349817344151
    ewmac4_16: 7.390837405733339e-18
    ewmac64_256: 0.10884349817344151
    ewmac8_32: 2.2924495189197003e-17
  GOLD:
    carry: 0.5187259451108088
    ewmac16_64: 0.0890880170247435
    ewmac2_8: 0.007919995531602834
    ewmac32_128: 0.10060949378644922
    ewmac4_16: 0.09266192131827346
    ewmac64_256: 0.11177439310939168
    ewmac8_32: 0.07922023411873078
  NZD:
    carry: 0.9999999999999948
    ewmac16_64: 2.387824329421832e-17
    ewmac2_8: 1.1810680791305428e-17
    ewmac32_128: 2.9532662700843846e-18
    ewmac4_16: 2.7837978717202566e-17
    ewmac64_256: 2.3331885739922672e-17
    ewmac8_32: 1.3253047924006077e-17
  SP500:
    carry: 0.4837629057367159
    ewmac16_64: 0.09443617365682141
    ewmac2_8: 0.014871415911043169
    ewmac32_128: 0.10620856269591358
    ewmac4_16: 0.09891500655961727
    ewmac64_256: 0.11765798351657271
    ewmac8_32: 0.08414795192331607

forecast_div_multiplier:
  BUND: 1.1563732765957708
  GOLD: 1.3746441626704793
  NZD: 1.000000000000016
  SP500: 1.3932121737433125

forecast_post_ceiling_cost_SR: 0.13
#
# Capital correction
#
percentage_vol_target: 25.0
notional_trading_capital: 50000
base_currency: "GBP"
#
# Portfolio creation
#
instrument_weights:
  BUND: 0.25
  GOLD: 0.25
  NZD: 0.25
  SP500: 0.25

instrument_div_multiplier: 1.93

#instruments:
#  - BUND
#  - GOLD
#  - NZD
#  - SP500

instruments: ['BUND','GOLD','NZD','SP500']

# MUST include at least first row in every config to override defaults!
ignore_instruments:
  - KOSPI # not supported on IG
  - GAS_US # too expensive
  - US2 # too expensive
  - V2X # too expensive

