#YAML
#
# Raw data
#
# Trading rules
#
trading_rules:
  ewmac2_8:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 2
         Lslow: 8
  ewmac4_16:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 4
         Lslow: 16
  ewmac8_32:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 8
         Lslow: 32
  ewmac16_64:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 16
         Lslow: 64
  ewmac32_128:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 32
         Lslow: 128
  ewmac64_256:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args: 
         Lfast: 64
         Lslow: 256
  carry:
     function: systems.provided.futures_chapter15.rules.carry2
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 90
#
use_forecast_scale_estimates: True
#
forecast_scalar_estimate:
   pool_instruments: True
#
# forecast combination
#
use_forecast_weight_estimates: True
use_forecast_div_mult_estimates: True
#
#
rule_variations: ['ewmac2_8','ewmac4_16','ewmac8_32','ewmac16_64','ewmac32_128','ewmac64_256']
#rule_variations: ['ewmac16_64','ewmac32_128','ewmac64_256','carry']
#rule_variations: ['ewmac16_64','ewmac32_128','ewmac64_256']
#
#
forecast_correlation_estimate:
   pool_instruments: True
#
use_instrument_weight_estimates: True
use_instrument_div_mult_estimates: True
#
#
#
# Capital correction
#
percentage_vol_target: 20.0
notional_trading_capital: 100000
base_currency: "GBP"
#
# Portfolio creation
#

# demo portfolio
instruments: ['BUND','GOLD','NZD','SP500']

# filtered (costs < 0.08) batch 1
#instruments: ['AEX','BTP','BUND','CAC','COPPER','CORN','CRUDE_W','EUROSTX','GBP','GOLD','LEANHOG','NASDAQ','NZD','OAT','PLAT','SMI','SOYBEAN','SP500','US10','US5','WHEAT']

# full batch 1
#instruments: ['AEX','AUD','BOBL','BTP','BUND','CAC','COPPER','CORN','CRUDE_W','EDOLLAR','EUR','EUROSTX','GAS_US','GBP','GOLD','JPY','LEANHOG','LIVECOW','NASDAQ','NZD','OAT','PALLAD','PLAT','SHATZ','SMI','SOYBEAN','SP500','US10','US2','US5','V2X','VIX','WHEAT']

# full batch 2
#instruments: ["ASX","DAX","FTSE","HANG","NIKKEI","DOW","RUSSELL","US30","USTB","BUXL","GILT","JGB","EURIBOR","SSTERL","EURGBP","CAD","CHF","DOLLAR","BRENT_W","GASOLINE","HEATOIL","GASOIL_LDN","SILVER","CARBON","COFFEE","COTTON","SOYOIL","SUGAR","LUMBER","OATIES","COCOA_NY","COCOA_LDN","SUGAR_LDN","COFFEE_LDN","OJ","SOYMEAL","WHEAT_LDN","RICE"]

# MUST include this in every config!
ignore_instruments:
  - KOSPI